config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'home#index'
  resources :appointments
  resources :client_intake_forms do
    member do
      get 'generate_pdf'
    end
  end
  resources :companies do
    resources :appointments
  end
  resources :memberships, only: %i[new create edit patch update]
  resources :employment_application_forms, path: 'employees'
end

app/controllers/employment_application_forms_controller.rb
class EmploymentApplicationFormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employment_application_form, only: %i[show edit update destroy]

  # index
  def index
    @employment_application_forms = EmploymentApplicationForm.includes(:user, :company).where(company_id: current_user.companies)
  end

  # new
  def new
    @employment_application_form = EmploymentApplicationForm.new
    @companies = current_user.companies
    @company_id = params[:company_id]
    @users = User.all
  end

  # create
  def create
    @employment_application_form = EmploymentApplicationForm.new(employment_application_form_params)

    respond_to do |format|
      if @employment_application_form.save
        format.html do
          redirect_to employment_application_form_url(@employment_application_form)
        end
      else
        @error_message = @employment_application_form.errors.full_messages.first
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { error: @error_message }, status: :unprocessable_entity }
      end
    end
  end

  # show
  def show; end

  # edit
  def edit
    @companies = current_user.companies
    @users = User.all
  end
  
  # update
  def update
    respond_to do |format|
      if @employment_application_form.update(employment_application_form_params)
        format.html do
          redirect_to employment_application_form_url(@employment_application_form),
                      notice: 'Employee information was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @employment_application_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employment_application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # destroy
  def destroy
    @employment_application_form.destroy
    respond_to do |format|
      format.html { redirect_to employment_application_forms_url, notice: 'Employment application form was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private

  def set_employment_application_form
    @employment_application_form = EmploymentApplicationForm.find(params[:id])
  end

  def employment_application_form_params
    params.require(:employment_application_form).permit(
      :company_id,
      :user_id,
      :preferred_name,
      :gender,
      :alternate_phone_number,
      :additional_info
    )
  end
end

app/helpers/employment_application_forms_helper.rb
module EmploymentApplicationFormsHelper
  def selected_company_id(client_intake_form, company_id)
    if client_intake_form.persisted?
      client_intake_form.company_id
    else
      company_id
    end
  end
end

app/views/employment_application_forms/_employment_application_form.html.erb
<div id="<%= dom_id(employment_application_form) %>" class="mb-4 p-3">
  <div class="row">
      <div class="col">
        <strong>Company:</strong> <%= employment_application_form.company.name %>
      </div>
      <div class="col">
        <strong>User:</strong> <%= employment_application_form.user.email %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Preferred name:</strong> <%= employment_application_form.preferred_name %>
      </div>
      <div class="col">
        <strong>Gender:</strong> <%= employment_application_form.gender %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Alternate phone number:</strong> <%= employment_application_form.alternate_phone_number %>
      </div>
      <div class="col">
        <strong>Additional info:</strong> <%= employment_application_form.additional_info %>
      </div>
    </div>
</div>

app/views/employment_application_forms/_form.html.erb
<%= form_with(model: employment_application_form) do |form| %>
  <% if employment_application_form.errors.any? %>
   <div class="alert alert-danger">
      <h2><%= pluralize(employment_application_form.errors.count, "error") %> prohibited this employment application form from being saved:</h2>

      <ul>
        <% employment_application_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :company_id, class: "form-label" %>
    <% if @companies.any? %>
      <%= form.select :company_id, options_for_select(@companies.map { |company| [company.name, company.id] }, selected_company_id(employment_application_form, @company_id)), {}, class: "form-select" %>
    <% else %>
      <%= form.select :company_id, {}, {}, class: "form-select", disabled: true %>
      <p class="text-muted">You don't have any companies.</p>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <% options = @users.map { |user| [user.email, user.id] } %>
    <%= form.select :user_id, options_for_select(options, selected: employment_application_form.user_id), { required: true }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :preferred_name, class: "form-label" %>
    <%= form.text_field :preferred_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :gender, class: "form-label" %>
    <%= form.select :gender, options_for_select(['Male', 'Female', 'Other'], selected: employment_application_form.gender), { prompt: 'Select Gender' }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :alternate_phone_number, class: "form-label" %>
    <%= form.text_field :alternate_phone_number, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :additional_info, class: "form-label" %><br>
    <%= form.text_area :additional_info, class: "form-control" %>
  </div>

  <%= form.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", @employment_application_form, class: "btn btn-secondary ms-2" %>
<% end %>

app/views/employment_application_forms/edit.html.erb
<div class="container">
  <h1>Edit Employee Information - #<%= @employment_application_form.id %></h1>

  <div class="mb-4 border p-3">
    <%= render "form", employment_application_form: @employment_application_form %>
  </div>
</div>

app/views/employment_application_forms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Employees</h1>
    </div>
  </div>

  <%= link_to "Add", new_employment_application_form_path, class: "btn btn-primary mb-3" %>
  <%= link_to "Back Home", root_path, class: "btn btn-secondary mb-3" %>

  <div class="row">
    <div class="col">
      <% if @employment_application_forms.present? %>
        <% @employment_application_forms.each do |employment_application_form| %>
          <div class="mb-4 border p-3 employment-application-form" style="cursor: pointer;" onclick="window.location='<%= employment_application_form_path(employment_application_form) %>';">
            <%= render employment_application_form %>
          </div>
        <% end %>
      <% else %>
        <div class="border p-5">
          <p><em>No employees found.</em></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/employment_application_forms/new.html.erb
<div class="container">

  <div class="text-end mb-4">
    <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
  </div>

  <div class="mb-4 border p-3">
    <h1>New Employee Application Form</h1>

  <%= render "form", employment_application_form: @employment_application_form  %>

  </div>
</div>

app/views/employment_application_forms/show.html.erb
<div class="container">
  <div class="mb-3">
    <h1 class="d-inline">Employment Application Form - #<%= @employment_application_form.id %></h1>

    <div class="float-end">
      <%= link_to "Back to Company", company_path(@employment_application_form.company_id), class: "btn btn-secondary ms-2" %>
    </div>
  </div>

  <div class="mb-4 border p-3">
    <%= render @employment_application_form %>
  </div>

  <div class="row">
    <div class="mb-4">
      <%= link_to "Edit Form", edit_employment_application_form_path(@employment_application_form), class: "btn btn-primary me-2" %>
    </div>
    <div class="col-md-10 text-left">
      <%= button_to "Delete Form", @employment_application_form, method: :delete, data: { turbo_confirm: "Are you sure you want to delete the form?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>