config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'home#index'
  resources :appointments
  resources :client_intake_forms do
    member do
      get 'generate_pdf'
    end
  end
  resources :companies do
    resources :appointments
  end
  resources :memberships, only: %i[new create edit patch update]
  resources :employment_application_forms, path: 'employees'
end

app/controllers/client_intake_forms_controller.rb
class ClientIntakeFormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client_intake_form, only: %i[show edit update destroy]

  # GET /client_intake_forms or /client_intake_forms.json
  def index
    @client_intake_forms = ClientIntakeForm.all
  end

  # GET /client_intake_forms/1 or /client_intake_forms/1.json
  def show; end

  # GET /client_intake_forms/new
  def new
    @client_intake_form = ClientIntakeForm.new
    @companies = current_user.companies
    @company_id = params[:company_id]
    @users = User.all
  end

  # GET /client_intake_forms/1/edit
  def edit
    @companies = current_user.companies
    @users = User.all
  end

  # POST /client_intake_forms or /client_intake_forms.json
  def create
    @client_intake_form = ClientIntakeForm.new(client_intake_form_params)

    respond_to do |format|
      if @client_intake_form.save
        format.html do
          redirect_to client_intake_form_url(@client_intake_form),
                      notice: 'Client intake form was successfully created.'
        end
        format.json { render :show, status: :created, location: @client_intake_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client_intake_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_intake_forms/1 or /client_intake_forms/1.json
  def update
    respond_to do |format|
      if @client_intake_form.update(client_intake_form_params)
        format.html do
          redirect_to client_intake_form_url(@client_intake_form),
                      notice: 'Client intake form was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @client_intake_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client_intake_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_intake_forms/1 or /client_intake_forms/1.json
  def destroy
    @client_intake_form.destroy!

    respond_to do |format|
      format.html { redirect_to client_intake_forms_url, notice: 'Client intake form was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def generate_pdf
    @client_intake_form = ClientIntakeForm.find(params[:id])

    pdf = ClientIntakeFormPdf.new(@client_intake_form)
    send_data pdf.render,
              filename: 'client_intake_form.pdf',
              type: 'application/pdf',
              disposition: 'inline'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client_intake_form
    @client_intake_form = ClientIntakeForm.includes(:user).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_intake_form_params
    params.require(:client_intake_form).permit(
      :company_id,
      :user_id,
      :first_name,
      :last_name,
      :preferred_name,
      :email_address,
      :gender,
      :phone_number,
      :alternate_phone_number,
      :date_of_birth,
      :address,
      :city,
      :province,
      :country,
      :additional_info
    )
  end
end

app/helpers/client_intake_forms_helper.rb
module ClientIntakeFormsHelper

  def selected_company_id(client_intake_form, company_id)
    if client_intake_form.persisted?
      client_intake_form.company_id
    else
      company_id
    end
  end
end

app/views/client_intake_forms/_client_intake_form.html.erb
<div id="<%= dom_id(client_intake_form) %>" class="mb-4 p-3">
  <div class="row">
    <div class="col">
      <strong>Company:</strong> <%= client_intake_form.company.name %>
    </div>
    <div class="col">
      <strong>User:</strong>
      <% if client_intake_form.user %>
        <%= "#{client_intake_form.user_id} - #{client_intake_form.user.email}" %>
      <% else %>
        <em>
          No user associated with this client intake form.
          <%= link_to "Edit", edit_client_intake_form_path(@client_intake_form) %>
        </em>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>First name:</strong> <%= client_intake_form.first_name %>
    </div>
    <div class="col">
      <strong>Last name:</strong> <%= client_intake_form.last_name %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Preferred name:</strong> <%= client_intake_form.preferred_name %>
    </div>
    <div class="col">
      <strong>Email address:</strong> <%= client_intake_form.email_address %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Gender:</strong> <%= client_intake_form.gender %>
    </div>
    <div class="col">
      <strong>Phone number:</strong> <%= client_intake_form.phone_number %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Date of birth:</strong> <%= client_intake_form.date_of_birth %>
    </div>
    <div class="col">
      <strong>Address:</strong> <%= client_intake_form.address %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>City:</strong> <%= client_intake_form.city %>
    </div>
    <div class="col">
      <strong>Province:</strong> <%= client_intake_form.province %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Country:</strong> <%= client_intake_form.country %>
    </div>
    <div class="col">
      <strong>Alternate phone number:</strong> <%= client_intake_form.alternate_phone_number %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Additional info:</strong> <%= client_intake_form.additional_info %>
    </div>
  </div>
</div>

app/views/client_intake_forms/_form.html.erb
<%= form_with(model: client_intake_form) do |form| %>
  <% if client_intake_form.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(client_intake_form.errors.count, "error") %> prohibited this client intake form from being saved:</h2>

      <ul>
        <% client_intake_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :company_id, class: "form-label" %>
    <% if @companies.any? %>
      <%= form.select :company_id, options_for_select(@companies.map { |company| [company.name, company.id] }, selected_company_id(client_intake_form, @company_id)), {}, class: "form-select" %>
    <% else %>
      <%= form.select :company_id, {}, {}, class: "form-select", disabled: true %>
      <p class="text-muted">You don't have any companies.</p>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <% options = [['No User', '']] + @users.map { |user| [user.email, user.id] } %>
    <%= form.select :user_id, options_for_select(options, selected: client_intake_form.user_id), { required: true }, class: "form-select" %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= form.label :first_name, class: "form-label" %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :last_name, class: "form-label" %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :preferred_name, class: "form-label" %>
      <%= form.text_field :preferred_name, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :email_address, class: "form-label" %>
    <%= form.text_field :email_address, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :gender, class: "form-label" %>
    <%= form.select :gender, options_for_select(['Male', 'Female', 'Other'], selected: client_intake_form.gender), { prompt: 'Select Gender' }, class: "form-select" %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= form.label :phone_number, class: "form-label" %>
      <%= form.text_field :phone_number, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :alternate_phone_number, class: "form-label" %>
      <%= form.text_field :alternate_phone_number, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :date_of_birth, class: "form-label" %>
      <%= form.date_field :date_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= form.label :city, class: "form-label" %>
      <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :province, class: "form-label" %>
      <%= form.text_field :province, class: "form-control" %>
    </div>
    <div class="col-md-4">
      <%= form.label :country, class: "form-label" %>
      <%= form.text_field :country, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :additional_info, class: "form-label" %><br>
    <%= form.text_area :additional_info, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", @client_intake_form, class: "btn btn-secondary ms-2" %>
  </div>
<% end %>

app/views/client_intake_forms/edit.html.erb
<div class="container">
  <h1>Edit Intake Form - #<%= @client_intake_form.id %></h1>

  <div class="mb-4 border p-3">
    <%= render "form", client_intake_form: @client_intake_form %>
  </div>
</div>

app/views/client_intake_forms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Client Intake Forms</h1>
    </div>
  </div>

  <%= link_to "New Client Intake Form", new_client_intake_form_path, class: "btn btn-primary mb-3" %>
  <%= link_to "Back Home", root_path, class: "btn btn-secondary mb-3" %>

  <div class="row">
    <div class="col">
      <% @client_intake_forms.each do |client_intake_form| %>
        <div class="mb-4 border p-3 client-intake-form" style="cursor: pointer;" onclick="window.location='<%= client_intake_form_path(client_intake_form) %>';">
          <%= render client_intake_form %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/client_intake_forms/new.html.erb
<div class="container">
  <div class="text-end mb-4">
    <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
    <%= link_to "All Client Intake Forms", client_intake_forms_path, class: "btn btn-secondary" %>
  </div>

  <!-- New Client Intake Form -->
  <div class="mb-4 border p-3">
    <h1>New Client Intake Form</h1>
    <%= render "form", client_intake_form: @client_intake_form %>
  </div>

</div>

app/views/client_intake_forms/show.html.erb
<div class="container">
  <h1 class="d-inline">Client Intake Form - #<%= @client_intake_form.id %></h1>

  <div class="float-end mb-4">
    <%= link_to "Back to Company", company_path(@client_intake_form.company_id), class: "btn btn-secondary ms-2" %>
  </div>

  <div class="mb-4 border p-3">
    <%= render @client_intake_form %>
  </div>

  <div class="row">
    <div class="col-2">
      <%= button_to "Generate PDF", generate_pdf_client_intake_form_path(@client_intake_form), method: :get, class: "btn btn-primary", form: {target: '_blank'} %>
    </div>
    <div class="col-2">
      <%= link_to "Edit Form", edit_client_intake_form_path(@client_intake_form), class: "btn btn-primary me-2" %>
    </div>
    <div class="col-2">
      <%= button_to "Delete Form", @client_intake_form, method: :delete, data: { turbo_confirm: "Are you sure you want to delete the form?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>