config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'home#index'
  resources :appointments
  resources :client_intake_forms do
    member do
      get 'generate_pdf'
    end
  end
  resources :companies do
    resources :appointments
  end
  resources :memberships, only: %i[new create edit patch update]
  resources :employment_application_forms, path: 'employees'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :company

  validate :appointment_time_in_future

  private

  def appointment_time_in_future
    if appointment_time.present? && appointment_time <= Time.now
      errors.add(:appointment_time, "must be in the future")
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: %i[show edit update destroy]

  def index
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @upcoming_appointments = @company.appointments.where('appointment_time >= ?', Time.now)
      @past_appointments = @company.appointments.where('appointment_time < ?', Time.now)
    else
      @upcoming_appointments = current_user.appointments.where('appointment_time >= ?', Time.now)
      @past_appointments = current_user.appointments.where('appointment_time < ?', Time.now)
    end
  end

  def new
    @appointment = Appointment.new(company_id: params[:company_id], user_id: current_user.id)
    @duration_options = duration_options
    @companies = Company.all
    @users = User.all
  end

  def show; end

  def create
    @appointment = current_user.appointments.new(appointment_params)

    begin
      if @appointment.save
        redirect_to @appointment, notice: 'Appointment was successfully created.'
      else
        @error_message = @appointment.errors.full_messages.first
        redirect_to new_appointment_path, alert: @error_message
      end
    rescue ActionController::ParameterMissing => e
      flash.now[:alert] = "Missing parameter: #{e.param}"
      render :new
    rescue ActionController::UnpermittedParameters => e
      flash.now[:alert] = "Unpermitted parameter: #{e.params}"
      render :new
    end
  end

  def edit
    @duration_options = duration_options
  end

  def update
    if @appointment.update(appointment_params)
      notice_msg = 'Appointment was successfully updated.'
    else
      @duration_options = duration_options
      notice_msg = @appointment.errors.full_messages.join('. ')
    end
    redirect_to @appointment, notice: notice_msg
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Appointment was successfully deleted.'
  end

  private

  def set_appointment
    @appointment = current_user.appointments.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:company_id, :user_id, :appointment_time, :duration)
  end

  def duration_options
    (15..420).step(15).map { |minutes| [format_duration(minutes), minutes] }
  end

  def format_duration(minutes)
    hours = minutes / 60
    minutes_left = minutes % 60
    "#{hours} hours #{minutes_left} minutes"
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.html.erb
<div class="container">
  <!-- Edit Appointment Form -->
  <div class="mb-4 border p-3">
    <h1>Edit Appointment</h1>
    <%= form_with(model: @appointment, url: appointment_path(@appointment), method: :patch) do |f| %>
      <div class="col-md-6">
        <div class="mb-3">
          <%= f.label :company_id, "Select Company", class: "form-label" %>
          <%= f.collection_select :company_id, Company.all, :id, :name, selected: @appointment.company_id, class: "form-select" %>
        </div>

        <div class="mb-3">
          <%= f.label :user_id, "Select User", class: "form-label" %>
          <%= f.collection_select :user_id, User.all, :id, :email, selected: @appointment.user_id, class: "form-select" %>
        </div>

        <div class="mb-3">
          <%= f.label :appointment_time, class: "form-label" %>
          <%= f.datetime_field :appointment_time, value: @appointment.appointment_time, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :duration, class: "form-label" %>
          <%= f.select :duration, options_for_select(@duration_options, @appointment.duration), class: "form-select" %>
        </div>

        <div class="mb-3"></div> <!-- Empty div for spacing -->

        <div class="actions">
          <%= f.submit "Update Appointment", class: "btn btn-primary me-2" %>
          <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="container">
  <!-- Back Home Button -->
  <div class="text-end mb-2">
    <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
  </div>

  <!-- Your Appointments -->
  <div class="mb-4 border p-3">
    <h1>Appointments</h1>

    <% if @upcoming_appointments.any? %>
      <h2>Upcoming Appointments</h2>
      <% @upcoming_appointments.each do |appointment| %>
        <div class="mb-4">
          <ul class="list-unstyled">
            <li><strong>Company:</strong> <%= appointment.company.name %></li>
            <li><strong>User:</strong> <%= appointment.user.email %></li>
            <li><strong>Date and Time:</strong> <%= appointment.appointment_time.strftime("%Y-%m-%d %H:%M:%S") %></li>
            <li><strong>Status:</strong> <%= appointment.status %></li>
            <li><strong>Duration:</strong> <%= appointment.duration %> minutes</li>
            <li><strong>Price:</strong> <%= appointment.price %></li>
          </ul>
          <div class="btn-group mt-2" role="group">
            <%= link_to "Edit", edit_appointment_path(appointment), class: "btn btn-secondary me-2" %>
            <%= button_to "Delete", appointment, method: :delete, data: { turbo_confirm: "Are you sure you want to delete this appointment?" }, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No upcoming appointments found.</p>
    <% end %>

    <% if @past_appointments.any? %>
      <h2>Past Appointments</h2>
      <% @past_appointments.each do |appointment| %>
        <div class="mb-4">
          <ul class="list-unstyled">
            <li><strong>Company:</strong> <%= appointment.company.name %></li>
            <li><strong>User:</strong> <%= appointment.user.email %></li>
            <li><strong>Date and Time:</strong> <%= appointment.appointment_time.strftime("%Y-%m-%d %H:%M:%S") %></li>
            <li><strong>Status:</strong> <%= appointment.status %></li>
            <li><strong>Duration:</strong> <%= appointment.duration %> minutes</li>
            <li><strong>Price:</strong> <%= appointment.price %></li>
          </ul>
          <div class="btn-group mt-2" role="group">
            <%= link_to "Edit", edit_appointment_path(appointment), class: "btn btn-secondary me-2" %>
            <%= button_to "Delete", appointment, method: :delete, data: { turbo_confirm: "Are you sure you want to delete this appointment?" }, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No past appointments found.</p>
    <% end %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container">
  <!-- Back Home Button -->
  <div class="text-end mb-4">
    <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
  </div>

  <!-- New Appointment Form -->
  <div class="mb-4 border p-3">
    <h1>New Appointment</h1>
    <%= form_with(model: @appointment, url: appointments_path, method: :post) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="mb-3">
            <%= f.label :appointment_time, class: "form-label" %>
            <%= f.datetime_field :appointment_time, min: Time.now.strftime("%Y-%m-%dT%H:%M"), class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :company_id, "Select Company", class: "form-label" %>
            <%= f.collection_select :company_id, @companies, :id, :name, { prompt: "Select a company" }, { required: true, class: "form-select" } %>
          </div>

          <div class="mb-3">
            <%= f.label :user_id, "Select User", class: "form-label" %>
            <%= f.collection_select :user_id, @users, :id, :email, { prompt: "Select a user" }, required: true, class: "form-select" %>
          </div>
          <div class="mb-3">
            <%= f.label :duration, class: "form-label" %>
            <%= f.select :duration, options_for_select(@duration_options, @appointment.duration), required: true, class: "form-select" %>
          </div>
          <div class="actions">
            <%= f.submit "Create Appointment", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="container">
  <!-- Appointment Details -->
  <div class="mb-4 border p-3">
    <h1>Appointment Details</h1>
    <div class="row">
      <div class="col-md-6">
        <p><strong>Company:</strong> <%= @appointment.company.name %></p>
        <p><strong>Date:</strong> <%= @appointment.appointment_time.strftime("%Y-%m-%d %H:%M:%S") %></p>
        <p><strong>Status:</strong> <%= @appointment.status %></p>
        <p><strong>Duration:</strong> <%= @appointment.duration %> minutes</p>
        <p><strong>Price:</strong> <%= @appointment.price %></p>
      </div>
    </div>
    <!-- Action buttons -->
    <div class="row mt-3">
      <div class="col-md-6">
        <%= link_to "Edit", edit_appointment_path(@appointment), class: "btn btn-primary me-2" %>
        <%= link_to "Back Home", root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>